### PR TITLE
can transfer erc20 token to hrc20 token in a truly decentralised trustless fashion

### PR DESCRIPTION
**Pull request by harshabakku**
horizon trustless bridge from eth to harmony (end to end tested uni directional as of now)

can transfer erc20 token to hrc20 token in a truly decentralised trustless fashion as of now.

- [ ] elc   //done
- [ ] everifier  //done
- [ ] eprover //done
- [ ] hlc  //reference contracts added, can be deployed by creating equivalent  elc/ethClient/test/deploy.js to deploy to hmy
- [ ] hverifier //done
- [ ] hprover //all the code is there, hmy_getProof does not works, unable to get merkle proofs of hmy txs
- [ ] ethtohmy relayer  //done
- [ ] hmytoeth relayer  //reference code added
- [ ] cli //done 

repos used (code reused/enhanced):

1. https://github.com/near/rainbow-bridge  //cli and eth2-hmy relayer code
2. https://github.com/JackyWYX/harmony_rainbow  //everifier, eprover, hverifier, hprover,  bridge contracts
3. https://github.com/rlan35/ethClient  // ethclient contract

development was done sticking to the documentation, clear cut comments added,  commit messages explaining clear progress every step of the way,

README.md documentation to run, test, deploy added , sample logs included in horizon/logs folder

 for more info on the work please also watch hackathon submission video
https://www.youtube.com/watch?v=TceBfqmSAbQ&ab_channel=HarshaBakku

### CODE REVIEW

**Comment by gupadhyaya** [comment]
@harshabakku thanks for your PR. we will review soon and get back to you.

**Comment by peekpi** [comment]
@harshabakku  hey, thanks for your PR. The trustless bridge is still under development, the latest code can be seen here:
- Bridge: #3
- ELC: #2
And some contracts you used are semi-finished.😂

**Comment by harshabakku** [comment]
good work @peekpi , I understand that elc contracts are semi-finished, and I wanted to submit something that works end-end to testnet so further development can continue. but looks like a lot has been developed in last 2 months 

to give u an update 
 my code does not really have block provers( validating merkfle proofs of dag entries), it  only validates merkle proofs of  transaction logs.

also note that I'm happy to help if you want to use my cli, relayers or any submodule of my code.

**Comment by peekpi** [comment]
@harshabakku there is definitely some code that can be used. But the project is still under development and many interfaces will change, so it is difficult to merge them directly.

**Comment by harshabakku** [comment]
thanks @peekpi,  not a problem at all, (if cant be merged directly)

**Pull request closed without merging**
